export const NAME_SERVICE_GRPC = {
  USER_SERVICE: 'UserService',
  USER_PACKAGE: 'user',
  ORDER_SERVICE: 'OrderService',
  ORDER_PACKAGE: 'order',
  PRODUCT_SERVICE: 'ProductService',
  PRODUCT_PACKAGE: 'product',
  INVENTORY_SERVICE: 'InventoryService',
  INVENTORY_PACKAGE: 'inventory',
  PAYMENT_SERVICE: 'PaymentService',
  PAYMENT_PACKAGE: 'payment',
  SEARCH_SERVICE: 'SearchService',
  SEARCH_PACKAGE: 'search',
  STORAGE_SERVICE: 'StorageService',
  STORAGE_PACKAGE: 'storage',
};
