export const PORT_GRPC = {
  USER_PORT_GRPC: 50051,
  PRODUCT_PORT_GRPC: 50052,
  ORDER_PORT_GRPC: 50053,
  INVENTORY_PORT_GRPC: 50054,
};

export const NAME_SERVICE_GRPC = {
  USER_SERVICE: 'USER_SERVICE',
  USER_PACKAGE: 'user',
  ORDER__SERVICE: 'ORDER_SERVICE',
  ORDER_PACKAGE: 'order',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  PRODUCT_PACKAGE: 'product',
  INVENTORY_SERVICE: 'INVENTORY_SERVICE',
  INVENTORY_PACKAGE: 'inventory',
};
