version: '3.8'

services:
  redis-node-0:
    image: bitnami/redis:7.0
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_AOF_ENABLED=yes
    volumes:
      - redis_node0_data:/bitnami/redis/data
    ports:
      - target: 6379
        published: 6379
        mode: host
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  redis-node-1:
    image: bitnami/redis:7.0
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_node1_data:/bitnami/redis/data
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]
    depends_on:
      - redis-node-0

  redis-node-2:
    image: bitnami/redis:7.0
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_node2_data:/bitnami/redis/data
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]
    depends_on:
      - redis-node-0

  redis-sentinel-0:
    image: bitnami/redis-sentinel:7.0
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]
    depends_on:
      - redis-node-0

  redis-sentinel-1:
    image: bitnami/redis-sentinel:7.0
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]

  redis-sentinel-2:
    image: bitnami/redis-sentinel:7.0
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
    networks:
      - DevOps-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

volumes:
  redis_node0_data:
  redis_node1_data:
  redis_node2_data:

networks:
  DevOps-Network:
    external: true
