version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - target: 6379
        published: 6379
        mode: host
      - target: 8404
        published: 8404
        mode: host
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  redis-node-0:
    image: bitnami/redis:latest
    user: root
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=12345678
      - REDIS_AOF_ENABLED=yes
    volumes:
      - redis_node0_data:/bitnami/redis/data
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  redis-node-1:
    image: bitnami/redis:latest
    user: root
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=12345678
      - REDIS_PASSWORD=12345678
    volumes:
      - redis_node1_data:/bitnami/redis/data
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]
    depends_on:
      - redis-node-0

  redis-node-2:
    image: bitnami/redis:latest
    user: root
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=12345678
      - REDIS_PASSWORD=12345678
    volumes:
      - redis_node2_data:/bitnami/redis/data
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]
    depends_on:
      - redis-node-0

  redis-sentinel-0:
    image: bitnami/redis-sentinel:latest
    user: root
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=12345678
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]
    depends_on:
      - redis-node-0

  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    user: root
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=12345678
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]

  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    user: root
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_MASTER_HOST=redis-node-0
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=12345678
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

  mongo-node-0:
    image: mongo:4.4
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    volumes:
      - mongo_node0_data:/data/db
    ports:
      - '27018:27017'
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  mongo-node-1:
    image: mongo:4.4
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    volumes:
      - mongo_node1_data:/data/db
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]

  mongo-node-2:
    image: mongo:4.4
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    volumes:
      - mongo_node2_data:/data/db
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

  pg-master:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=12345678
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=slave_user
      - POSTGRESQL_REPLICATION_PASSWORD=12345678
      - POSTGRESQL_PGAUDIT_LOG=read,write
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - pg_master_data:/bitnami/postgresql
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  pg-slave1:
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_PASSWORD=12345678
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=slave_user
      - POSTGRESQL_REPLICATION_PASSWORD=12345678
    volumes:
      - pg_slave1_data:/bitnami/postgresql
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]

  pg-slave2:
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_PASSWORD=12345678
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=slave_user
      - POSTGRESQL_REPLICATION_PASSWORD=12345678
    volumes:
      - pg_slave2_data:/bitnami/postgresql
    networks:
      - Docker-Network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

volumes:
  redis_node0_data:
  redis_node1_data:
  redis_node2_data:
  mongo_node0_data:
  mongo_node1_data:
  mongo_node2_data:
  pg_master_data:
  pg_slave1_data:
  pg_slave2_data:

networks:
  Docker-Network:
    external: true

configs:
  haproxy_config:
    file: ./haproxy/haproxy.cfg
