version: '3.8'

services:
  # --- BROKER 0 (Chạy trên Worker 1) ---
  kafka-0:
    image: bitnami/kafka:3.6
    environment:
      # Định danh Node
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # Cấu hình Cluster (Quan trọng: Phải liệt kê cả 2 node)
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093

      # Cấu hình Mạng
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # 👇 CẤU HÌNH PARTITION & REPLICA (Theo yêu cầu của bạn)
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_IN_SYNC_REPLICAS=1

    volumes:
      - kafka_0_data:/bitnami/kafka
    networks:
      - kafka-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]

  # --- BROKER 1 (Chạy trên Worker 2) ---
  kafka-1:
    image: bitnami/kafka:3.6
    environment:
      # Định danh Node (Khác node 0)
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # Cấu hình Cluster giống hệt node 0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093

      # Cấu hình Mạng
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Cấu hình Partition & Replica
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_IN_SYNC_REPLICAS=1

    volumes:
      - kafka_1_data:/bitnami/kafka
    networks:
      - kafka-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

  # --- KAFKA UI (Quản lý cả 2 Broker) ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=my-cluster
      # Khai báo cả 2 broker để UI kết nối
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:9092,kafka-1:9092
    networks:
      - kafka-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

volumes:
  kafka_0_data:
  kafka_1_data:

networks:
  kafka-network:
    external: true
    name: Docker-Network
