version: '3.8'

services:
  # --- 1. ELASTICSEARCH (Logs & Data) ---
  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker1]
      resources:
        limits:
          memory: 1G

  # --- 2. KIBANA (UI cho Elastic) ---
  kibana:
    image: kibana:7.17.10
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  # --- 3. JAEGER (Tracing) ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-worker2]

  # --- 4. PROMETHEUS (Metrics) ---
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_targets
        target: /etc/prometheus/targets.json
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

  # --- 5. GRAFANA (Dashboard) ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3111:3111'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3111
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

volumes:
  elastic_data:
  prometheus_data:
  grafana_data:

configs:
  prometheus_config:
    file: ./prometheus.yml
  prometheus_targets:
    file: ./targets.json

networks:
  monitor-network:
    external: true
    name: Docker-Network
